-keep class com.spotify.** { *; }
-keep class com.fasterxml.** { *; }
-dontwarn com.fasterxml.**
-dontwarn org.w3c.dom.**
-dontwarn org.joda.time.**
-dontwarn org.shaded.apache.**
-dontwarn org.ietf.jgss.** 